db_path: ./db.json

timeout: 10
providers:
  ok:
    url: https://ccgfw.top/link/C7glPw7oQlPThsUV?mu=2
  dg:
    url: https://1b5a47dc025a1d3b27ffa811f3668dac.r7kq-2nfa-hg9x-bt4m-y3pw.sbs/s?t=1b5a47dc025a1d3b27ffa811f3668dac.jpg&route=1
    # ua: sing-box
  ft:
    url: https://ft-sub.tutunode.com/ft/tk/ce74fb7ae0efa99709c3cdbac2e38695
hosts:
  base: &base
    type: sing
    sudo: false
  camp-pk:
    <<: *base
    outbounds:
      - dg
    ssh_hostname: 10.73.64.4
    ssh_user: root
  camp-bb:
    <<: *base
    outbounds:
      - dg
    ssh_user: root
  # camp-box:
  #   <<: *base
  #   outbounds:
  #     - dg
  #   ssh_hostname: 10.73.64.8
  #   ssh_user: root
  mt3000-st:
    <<: *base
    outbounds:
      - dg
    ssh_hostname: 10.73.64.3
    ssh_user: root
  mt3000-ww:
    <<: *base
    outbounds:
      - dg
    ssh_hostname: 10.73.64.6
    ssh_user: root

github_proxy: https://ghfast.top/
