log:
  level: warn
  # output: box.log
  timestamp: true
dns:
  servers:
    - tag: dns_proxy
      address: https://dns.google/dns-query
      address_resolver: dns_resolver
      strategy: ipv4_only
      detour: proxy-out
    - tag: dns_direct
      address: tls://223.5.5.5
      # address_resolver: dns_resolver
      strategy: ipv4_only
      detour: direct
    - tag: dns_resolver
      address: 223.5.5.5
      strategy: ipv4_only
      detour: direct
    - tag: dns_success
      address: rcode://success
    - tag: dns_refused
      address: rcode://refused
    - tag: dns_fakeip
      address: fakeip
  before_rules:
    - outbound: any
      server: dns_resolver
    - rule_set: geosite-category-ads-all
      server: dns_refused
      action: route-options
      disable_cache: true
  after_rules:
    - rule_set:
        - geosite-geolocation-cn
      server: dns_direct
    - type: logical
      mode: and
      rules:
        - rule_set: geosite-geolocation-!cn
          invert: true
        - rule_set: geoip-cn
      server: dns_direct
    - domain_suffix:
        - limao.tech
        - ftiasch.xyz
      server: dns_direct
    - type: logical
      mode: and
      rules:
        - rule_set: geosite-geolocation-!cn
          invert: true
        - ip_is_private: true
      server: dns_proxy
      client_subnet: 223.5.5.5/24
  final: dns_proxy
  independent_cache: false
  cache_capacity: 1048576
  fakeip:
    enabled: true
    inet4_range: 198.18.0.0/15
    inet6_range: fc00::/18
route:
  rule_set: []
  before_rules:
    - inbound: tun-in
      action: sniff
    - protocol: dns
      ip_cidr: 223.5.5.5
      action: hijack-dns
    - rule_set: geoip-cn
      outbound: direct
    - ip_is_private: true
      outbound: direct
    - rule_set: geosite-geolocation-cn
      outbound: direct
    - type: logical
      mode: and
      rules:
        - rule_set: geosite-geolocation-!cn
          invert: true
        - rule_set: geoip-cn
      outbound: direct
    # - rule_set:
    #     - geosite-adobe@cn
    #     - geosite-apple@cn
    #     - geosite-category-games-cn
    #     - geosite-microsoft@cn
    #   outbound: direct
  after_rules:
    # - port: 853
    #   network: tcp
    #   outbound: direct
    # - port: 443
    #   network: udp
    #   outbound: direct
    # - port: 123 # NTP
    #   outbound: direct
    # - port: 3478 # stun
    #   outbound: direct
    # - port: 11010 # easytier
    #   outbound: direct
    # - port: 11011 # easytier
    #   outbound: direct
    - port: 22000 # syncthing
      outbound: direct
  final: proxy-out
  auto_detect_interface: true
inbounds:
  - type: tun
    tag: tun-in
    interface_name: tun0
    address:
      - 172.16.0.1/30
      - fd00::1/126
    mtu: 1492
    auto_route: true
    # auto_redirect: true
    strict_route: true
    stack: system
  - type: mixed
    tag: http-in
    listen: "::"
    listen_port: 8001
outbounds:
  - type: direct
    tag: direct
experimental:
  cache_file:
    enabled: true
    path: cache.db
    store_fakeip: true
    store_rdrc: true
  clash_api:
    external_controller: 0.0.0.0:9090
    access_control_allow_origin:
      - http://127.0.0.1
      - https://metacubexd.pages.dev
      - https://yacd.haishan.me
    access_control_allow_private_network: true

